# The provider and backend blocks are generated by Terragrunt from
# infra/root.hcl, so they are deliberately absent here. Running this module
# with bare terraform/tofu will not work, and is not meant to.

terraform {
  required_version = ">= 1.10"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
    archive = {
      source  = "hashicorp/archive"
      version = "~> 2.7"
    }
  }
}
